config/routes.rb
Rails.application.routes.draw do
  get 'idelve/new'
  get 'idelve/show'
  get 'idelve/iam'
  get 'idelve/iwish'
  get 'idelve/iconnect'
  get 'idelve/upload'
  get 'idelve/home'
  get 'idelve/profile'
  get 'idelve/team'
  get 'idelve/resume'

  post 'idelve/upload', to: 'idelve#do_upload'

  get 'skill/list'
  get 'skill/add'
  post 'skill/create'
  get 'skill/show_resume'

  get 'medium/new'
  post 'medium/create'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'idelve#home'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medium.rb
class Medium < ApplicationRecord
  has_attached_file :data
  #validates_attachment_content_type :data, content_type: /\Aimage\/.*\z/
  #validates :data, attachment_presence: true

  # change this later
  do_not_validate_attachment_file_type :data
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :medium

  def list
    @skills = current_user.skills
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :skills
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/idelve_controller.rb
class IdelveController < ApplicationController
  before_action :authenticate_user!

  skip_before_action :verify_authenticity_token

  def new
  end

  def home
  end

  def profile

  end

  def team

  end

  def iam
  end

  def iwish
  end

  def iconnect
  end

end

app/controllers/medium_controller.rb
class MediumController < ApplicationController
  def create
    @medium = Medium.create( medium_params )

    @medium.user_id = current_user.id
    @medium.save!

    current_user.lastupload = @medium.id
    current_user.save!
  end

  def new
    @medium = Medium.new
  end

  private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

  def medium_params
    params.require(:medium).permit(:data)
  end

end

app/controllers/skill_controller.rb
require 'bundler/setup'
require 'docx_templater'


class SkillController < ApplicationController
  def create
    @skill = Skill.create( skill_params )

    if (params[:use_last_upload]) then
      @skill.medium = Medium.find( current_user.lastupload )
    end

    @skill.user = current_user

    @skill.save!
  end


  def list
    @skills = current_user.skills
  end

  def add
    @skill = Skill.new

    current_user.lastscreen = skill_add_url
    current_user.save!
  end

  def show_resume
    send_data generate_resume(current_user),
              filename: "#{current_user.email}.docx",
              type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
              disposition: 'inline'
  end


  private

  def skill_params
    params.permit(:description)
  end

  def generate_resume(user)
    # TODO: user.skills -> data for resume
    @data = {
      name: 'Priya Vora',
      street: '14 Some Place',
      city: 'Honolulu',
      state: 'HI',
      zip_code: '96821',
      phone: '808-735-5555',
      email: 'priya@pvora.org',
      experience: [
        { job_date: 'Feb 2016 to present',
          job_experience: 'Foodland Market City' },
        { job_date: 'Feb 2015 to Dec 2015',
          job_experience: 'McDonalds Kaimukit' },
        { job_date: 'Oct 2014 to Feb 2015',
          job_experience: 'Hilo Hattie' },
        { job_date: 'Jun 2013 to July 2014',
          job_experience: 'Goodwill Industries' },
        { job_date: 'Jun 2012 to July 2013',
          job_experience: 'Lanakila' },
        { job_date: 'Jun 2011 to July 2012',
          job_experience: 'McDonalds Kaimuki' },
        { job_date: 'Jan 2011 to Jun 2011',
          job_experience: 'Goodwill Industries' },
        { job_date: 'Aug 2010 to Jan 2011',
          job_experience: 'Lanakila' },
        { job_date: 'Jun 2009 to July 2010',
          job_experience: 'Goodwill Industries' },
        { job_date: 'Jun 2008 to July 2009',
          job_experience: 'Lanakila' }
      ],
      education: [
        { education_date: 'Jun 2008',
          education_description: 'Lanakila School' },
        { education_date: 'Jun 2007',
          education_description: 'Jefferson Elementary School' }
      ],
      skill: [
        { skill_category: 'Reading Level',
          skill_list: '6th grade' },
        { skill_category: 'Basic Math',
          skill_list: 'count inventory, simple addition and subtraction' },
        { skill_category: 'Independent Work',
          skill_list: 'restock shelves, sweep floor, mop floor, throw out trash' },
      ]
    }

    template = 'lib/assets/template-resume.docx'
    DocxTemplater::DocxCreator.new(template, @data).generate_docx_bytes().string
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idelve_helper.rb
module IdelveHelper
end

app/helpers/medium_helper.rb
module MediumHelper
end

app/helpers/skill_helper.rb
module SkillHelper
end

app/views/idelve/home.html.erb
<h1 class="app-title">iDelve</h1>
<p style="text-align: center; color: #888888; font-size: 0.5em;">
  igniting Dignity Empathy Love Value Esteem
</p>
<div class="buttons-box">
  <div class="round-button profile-button">
    <div class="round-button-circle">
      <a href="<%= idelve_profile_url %>" title="About Me" class="round-button-link">&nbsp;</a>
    </div>
  </div>
  <div class="round-button team-button">
    <div class="round-button-circle">
      <a href="<%= idelve_team_url %>" title="My Team" class="round-button-link">&nbsp;</a>
    </div>
  </div>
  <div class="round-button resume-button">
    <div class="round-button-circle">
      <a href="<%= skill_list_url %>" title="My Resume" class="round-button-link">&nbsp;</a>
    </div>
  </div>
</div>
<p style="text-align: center;">
  Hello, <%=current_user.email %>!
  (<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>)
</p>
<div class="footer">
  <a href="<%=root_path%>"><i class="fa fa-home"></i></a>
  <i class="fa fa-share-alt"></i>
  <i class="fa fa-camera"></i>
  <i class="fa fa-cog"></i>
  <i class="fa fa-graduation-cap"></i>
</div>

app/views/idelve/iam.html.erb
<h1>iAm</h1>
<ul>
<li>i Am Amazing</li>
<li>i Am Valuable</li>
<li>i Am Needed</li>
<li>i Am Wanted</li>
<li>i Am Creative</li>
</ul>

<%= react_component('Item', name: 'Amazing', type: 'Trait') %>
<%= link_to "Home", root_path %>

app/views/idelve/iconnect.html.erb
<h1>iConnect</h1>
<p>Put content here!</p>



<%= link_to "Home", root_path %>

app/views/idelve/iwish.html.erb
<h1>iWish</h1>
<ul>
<li>i Wish I could fly</li>
<li>i Wish I could time travel</li>
</ul>
<%= link_to "Home", root_path %>

app/views/idelve/profile.html.erb
<h1 class="app-title">iAm</h1>
<p style="text-align: center; color: #888888; font-size: 0.5em;">
  igniting Abundant Mindfulness
</p>
<div class="row personal-info">
  <div class="col-md-4 i-am">
    <h2>I am...</h2>
    <ul>
      <li>I am creative.</li>
      <li>I am funny.</li>
      <li>I am loyal.</li>
    </ul>
    I am... <input type="text" />
  </div>
  <div class="col-md-4 i-can">
    <h2>I can...</h2>
    <ul>
      <li>I can lift 100 pounds.</li>
      <li>I can wash dishes.</li>
      <li>I can walk to the store.</li>
      <li>I can feed the dog.</li>
      <li>I can sing.</li>
    </ul>
    I can... <input type="text" />
  </div>
  <div class="col-md-4 i-like">
    <h2>I like...</h2>
    <ul>
      <li>I like to be around people.</li>
      <li>I like animals.</li>
      <li>I like being active.</li>
      <li>I like music.</li>
    </ul>
    I like... <input type="text" />
  </div>
</div>
<div class="footer">
  <a href="<%=root_path%>"><i class="fa fa-home"></i></a>
  <i class="fa fa-share-alt"></i>
  <i class="fa fa-camera"></i>
  <i class="fa fa-cog"></i>
  <i class="fa fa-graduation-cap"></i>
</div>

app/views/idelve/resume.html.erb
<h1 class="app-title">iDelve</h1>
<p style="text-align: center;">
  Hello, <%=current_user.email %>!
  (<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>)
</p>
<div class="buttons-box">
  <div class="round-button profile-button">
    <div class="round-button-circle">
      <a href="<%= idelve_iam_url %>" title="About Me" class="round-button-link">&nbsp;</a>
    </div>
  </div>
  <div class="round-button team-button">
    <div class="round-button-circle">
      <a href="http://www.google.com" title="My Team" class="round-button-link">&nbsp;</a>
    </div>
  </div>
  <div class="round-button resume-button">
    <div class="round-button-circle">
      <a href="<%= skill_list_url %>" title="My Resume" class="round-button-link">&nbsp;</a>
    </div>
  </div>
</div>
<div class="footer">
  <i class="fa fa-home"></i>
  <i class="fa fa-share-alt"></i>
  <i class="fa fa-camera"></i>
  <i class="fa fa-cog"></i>
  <i class="fa fa-graduation-cap"></i>
</div>

app/views/idelve/team.html.erb
<h1 class="app-title">iConnect</h1>
<p style="text-align: center; color: #888888; font-size: 0.5em;">
  igniting Career Oriented Needed Networks Elevating Compassionate Transactions
</p>
<div class="row contact">
  <div class="col-md-4"><img src="<%= asset_url("person2.png") %>"/></div>
  <div class="col-md-8">
    <h2>Mary Doe</h2>
    Mother</br>
    1234 Main Street</br>
    Waipahu, HI 96797</br>
    (808) 555-1234</br>
    <a href="mailto:mary.doe@thedoes.com">mary.doe@thedoes.com</a>
  </div>
</div>
<div class="row contact">
  <div class="col-md-4"><img src="<%= asset_url("person2.png") %>"/></div>
  <div class="col-md-8">
    <h2>Tanya Morita</h2>
    Employment Specialist</br>
    333 Sesame Street</br>
    Waipahu, HI 96797</br>
    (808) 555-4444</br>
    <a href="mailto:tanya.morita@empower.com">tanya.morita@empower.com</a>
  </div>
</div>
<div class="row contact">
  <div class="col-md-4"><img src="<%= asset_url("person2.png") %>"/></div>
  <div class="col-md-8">
    <h2>Gerry Wataru</h2>
    Co-worker</br>
    241 Oahu Street</br>
    Aiea, HI 96701</br>
    (808) 555-7439</br>
    <a href="mailto:gwataru@gmail.com">gwataru@gmail.com</a>
  </div>
</div>
<br/>
<div class="row">
  <div class="offset-md-4 col-md-8">
    <a href="#">Add new contact...</a>
  </div>
</div>

<div class="footer">
  <a href="<%=root_path%>"><i class="fa fa-home"></i></a>
  <i class="fa fa-share-alt"></i>
  <i class="fa fa-camera"></i>
  <i class="fa fa-cog"></i>
  <i class="fa fa-graduation-cap"></i>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iDelve</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div style="min-height: 920px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/medium/create.html.erb
Created.

<li>
  <%= link_to "Return", current_user.lastscreen %>
</li>

app/views/medium/new.html.erb
<%= form_for @medium, url: '/medium/create', html: {multipart: true} do |form|%>

  <%= form.file_field :data %>

  <%= form.submit %>

<% end %>

app/views/skill/add.html.erb
<h1> Add Skill </h1>

<%= form_for @skill, url: '/skill/create' do %>


<p>
<%= check_box_tag(:use_last_upload) %>
<%= label_tag(:use_last_upload, "Use last uploaded media:") %>
<%= Medium.find(current_user.lastupload).inspect  %>
</p>

<p>
  <%= link_to "Upload New Media", medium_new_url %>
</p>

<p>
  <%= label_tag(:description, "Description") %>
  <%= text_field_tag(:description ) %>
</p>


<%= submit_tag %>
<% end %>

app/views/skill/create.html.erb
Created.

<li>
  <%= link_to "Home", idelve_home_url %>
</li>

app/views/skill/list.html.erb
<h1 class="app-title">iWork</h1>
<p style="text-align: center; color: #888888; font-size: 0.5em;">
  igniting Winning Organized Resume Know-how
</p>

<div class="row">
  <div class="col-md-10 offset-md-1">

    <h2>My Resume</h2>

    <h3></h3>

    <%= link_to "Add a new skill", skill_add_url %>

    <% if @skills.blank? %>
        <p>Nothing yet</p>
    <% else %>
        <ul>
          <%= @skills.each do |item| %>
              <li>
                <%=item.description %> (<%=item.id %>)
              </li>
          <% end %>
        </ul>
    <% end %>

    <p><%= link_to "Download my resume", skill_show_resume_url, target: '_blank' %></p>
  </div>
</div>

<div class="footer">
  <a href="<%=root_path%>"><i class="fa fa-home"></i></a>
  <i class="fa fa-share-alt"></i>
  <i class="fa fa-camera"></i>
  <i class="fa fa-cog"></i>
  <i class="fa fa-graduation-cap"></i>
</div>

app/views/skill/show_resume.html.erb
<h1>My Resume</h1>
<%= show_resume %>